export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body data-new-gr-c-s-check-loaded="14.1223.0" data-gr-ext-installed="">
        <header style={{ backgroundColor: 'pink', padding: '12px' }}>
          <h1>Header</h1>
        </header>

        {children}

        <footer style={{ backgroundColor: 'aliceblue', padding: '12px' }}>
          <h1>Footer</h1>
        </footer>
      </body>
    </html>
  )
}
