import "../style.css";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  modal,
  children,
}: {
  modal: React.ReactNode,
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        {modal}
        {children}
      </body>
    </html>
  )
}
