import ErrorWrapper from '../error-wrapper';
import '../style.css';
import ThemeProvider from '../theme-provider';
export const metadata = {
  title: {
    default: 'Next.js',
    template: '%s | Gopal Gawade'
  },
  description: 'Generated by Next.js',
}

export default function GeneralLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <ThemeProvider>
        <body data-new-gr-c-s-check-loaded="14.1223.0" data-gr-ext-installed="">
          <header style={{ backgroundColor: 'lightgreen', padding: '12px' }}>
            <h1>Header</h1>
          </header>

          <ErrorWrapper>
            {children}
          </ErrorWrapper>

          <footer style={{ backgroundColor: 'aliceblue', padding: '12px' }}>
            <h1>Footer</h1>
          </footer>
        </body>
      </ThemeProvider>
    </html>
  )
}
